services:
  arzttermine.sabredav.controller:
    class: Arzttermine\SabreDavBundle\Controller\SabreDavController 
    arguments:
        - "@arzttermine.sabredav.server"
        - "@router"

  arzttermine.sabredav.server:
    class: Sabre\DAV\Server 
    arguments:
        - ["@arzttermine.sabredav_principal_collection", "@arzttermine.sabredav_caldav_collection"]

  arzttermine.sabredav_acl_plugin:
    class: Arzttermine\SabreDavBundle\SabreDav\ACLPlugin
    calls:
        - [setHideNodesFromListings, [true]]
        - [setAccessToNodesWithoutACL, [true]]

  arzttermine.sabredav_principal_plugin:
    class: Sabre\DAVACL\Plugin
    tags:
        - { name: sabredav.plugin }

  arzttermine.sabredav_principal_collection:
    class: Sabre\DAVACL\PrincipalCollection
    arguments:
        - "@arzttermine.sabredav_principal_backend"
    tags:
        - { name: sabredav.collection }

  arzttermine.sabredav_principal_backend:
    class: Arzttermine\SabreDavBundle\SabreDav\PrincipalBackend
    arguments:
        - "@doctrine.orm.entity_manager"
        - "@fos_user.user_manager"

  arzttermine.sabredav_caldav_plugin:
    class: Sabre\DAVACL\Plugin
    tags:
        - { name: sabredav.plugin }

  arzttermine.sabredav_caldav_collection:
    class: Sabre\CalDAV\CalendarRoot
    arguments:
        - "@arzttermine.sabredav_principal_backend"
        - "@arzttermine.sabredav_caldav_backend"
    tags:
        - { name: sabredav.collection }

  arzttermine.sabredav_caldav_backend:
    class: Arzttermine\SabreDavBundle\SabreDav\CalDavBackend
    arguments:
        - "@doctrine.orm.entity_manager"
